[package]
name = "rog-control-center"
license = "MPL-2.0"
version.workspace = true
authors = ["Luke D. Jones <luke@ljones.dev>"]
edition = "2021"

[features]
mocking = []

[dependencies]
egui = { git = "https://github.com/flukejones/egui", branch = "wayland_dark_theme" }
eframe= { git = "https://github.com/flukejones/egui", branch = "wayland_dark_theme" }

libappindicator = "0.7" # Tray icon
gtk = "0.15.5"

daemon = { path = "../daemon" }
rog_anime = { path = "../rog-anime" }
rog_dbus = { path = "../rog-dbus" }
rog_aura = { path = "../rog-aura" }
rog_profiles = { path = "../rog-profiles" }
rog_platform = { path = "../rog-platform" }
supergfxctl = { git = "https://gitlab.com/asus-linux/supergfxctl.git", default-features = false }
#supergfxctl = { path = "../../supergfxctl", default-features = false }

log.workspace = true
env_logger.workspace = true

tokio.workspace = true
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
zbus.workspace = true
dirs.workspace = true
notify-rust.workspace = true

png_pong.workspace = true

nix = "^0.26.1"
tempfile = "3.3.0"

# Translations
i18nx = "0.1.0"
formatx = "0.2.0"
